### ISSUE TITLE
Project scope

### ISSUE THREAD

**Issue by JedBorseth** [joshborseth/love-is-blind-bets#2]
Just at work right now but I wanted to get a better understanding of what the project is gonna be.

Is it gonna take payments? What are we betting with? If so how will this work? (stripe, etc.)

Betting is final when show starts?

What are you betting on? Who matches up with who? Who gets married?

**Comment by joshborseth** [comment]
okay so Im thinking lets not do payments

lets do one step for guessing who matches with who

then lets also allow users to guess who gets married.

they will have to guess before the show starts who matches with who, then they will have to guess who gets married after they reveal who the matches are in the show
